Fixed minor bugs and refactored code to put user in agora dir within container

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -30,11 +30,6 @@ RUN (apt-get -y install -y \
 #Remove Warnings
 RUN pip3 install --upgrade secretstorage
 
-#build gtest=
-# RUN cd /usr/src/gtest
-# RUN cmake CMakeLists.txt
-# RUN make
-
 # Install gtest and gflags
 RUN apt-get install -y libgtest-dev
 RUN cd /usr/src/gtest && \
@@ -43,7 +38,6 @@ RUN cd /usr/src/gtest && \
     mv lib/libgtest* /usr/lib/
 
 #Install inteloneAPI
-
 # use wget to fetch the Intel repository public key
 RUN cd /tmp
 RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
@@ -61,8 +55,10 @@ RUN tar xf armadillo-11.1.1.tar.xz
 RUN (cd armadillo-11.1.1; cmake .; make -j8; make install)
 RUN rm -rf armadillo*
 
+RUN mkdir Agora_dir;
+
 # Set up SoapySDR
-RUN ( \
+RUN ( cd Agora_dir; \
     git clone --branch soapy-sdr-0.8.1 --depth 1 --single-branch https://github.com/pothosware/SoapySDR.git;\
     cd SoapySDR; \
     mkdir build; \
@@ -74,7 +70,7 @@ RUN ( \
     )
 
 #SoapyRemote
-RUN ( \
+RUN ( cd Agora_dir;\
     git clone --branch soapy-remote-0.5.2 --depth 1 --single-branch https://github.com/pothosware/SoapyRemote.git; \
     cd SoapyRemote; \
     mkdir build; \
@@ -86,7 +82,7 @@ RUN ( \
     )
 
 #Iris drivers
-RUN ( \
+RUN ( cd Agora_dir;\
     git clone --branch rx-shorttimeout --depth 1 --single-branch https://github.com/Agora-wireless/sklk-soapyiris.git; \
     cd sklk-soapyiris; \
     mkdir -p build; \
@@ -97,19 +93,6 @@ RUN ( \
     cd ../..;\
     ldconfig; \
     )
-
-#RUN source /opt/intel/oneapi/setvars.sh --config="/opt/intel/oneapi/renew-config.txt"
-
-
-#RUN echo -e 'intelpython=exclude' | tee /opt/intel/oneapi/renew-config.txt
-# ENTRYPOINT ["echo", "-e", "'intelpython=exclude'", "|", "tee", "/opt/intel/oneapi/renew-config.txt"]
-
-# #RUN . /opt/intel/oneapi/setvars.sh --config="/opt/intel/oneapi/renew-config.txt"
-# ENTRYPOINT [".", "/opt/intel/oneapi/setvars.sh", " --config="/opt/intel/oneapi/renew-config.txt""]
-
-# ENTRYPOINT ["echo", "-e", "'#!/usr/bin/bash\nsource /opt/intel/oneapi/setvars.sh --config="/opt/intel/oneapi/renew-config.txt"'", ""]
-# RUN echo -e '#!/usr/bin/bash\nsource /opt/intel/oneapi/setvars.sh --config="/opt/intel/oneapi/renew-config.txt"' | tee /etc/profile.d/10-inteloneapivars.sh
-# #Enable the soapy sdr server for more robust device detection
 
 RUN systemctl enable SoapySDRServer
 
@@ -126,70 +109,16 @@ RUN (cd /opt/ \
     rm -rf .git \
     rm .gitignore)
 
-# Install FlexRAN FEC SDK
+#Clone Agora
+RUN (cd Agora_dir; \
+    git clone --branch develop https://github.com/enteraga6/Agora agora || \
+    { echo "Failed to clone git repository: https://github.com/enteraga6/Agora" && exit 1; })
 
-# RUN (WIRELESS_SDK_TARGET_ISA="avx512" && \
-#     export WIRELESS_SDK_TARGET_ISA &&\
-#     cd /opt/FlexRAN-FEC-SDK-19-04/sdk && \
-#     ./create-makefiles-linux.sh && \
-#     cd build-avx512-icc &&\
-#     make -j &&\
-#     make install)
-
+# # Install FlexRAN FEC SDK
 COPY ./entry_script.sh ./opt
 RUN ["chmod", "+x", "./opt/entry_script.sh"]
 
 ENTRYPOINT ["/bin/bash", "-c", "./opt/entry_script.sh"]
 
-# RUN (. /opt/intel/oneapi/setvars.sh --config="/opt/intel/oneapi/renew-config.txt" \
-#     cd /opt/FlexRAN-FEC-SDK-19-04/sdk \
-#     rm -rf build-avx* \ 
-#     WIRELESS_SDK_TARGET_ISA="avx2" \
-#     export WIRELESS_SDK_TARGET_ISA \
-#     . create-makefiles-linux.sh \
-#     cd build-avx2-icc \
-#     make -j \
-#     make install)
-
-# RUN ldconfig
-
-
-# RUN (cd ./agora \
-#     chown ${USER}:${GROUP} . \
-#     chmod 775 . \
-#     mkdir ./agora/build)
-
-#Clone Agora
-RUN (git clone --branch develop https://github.com/enteraga6/Agora agora || \
-    { echo "Failed to clone git repository: https://github.com/enteraga6/Agora" && exit 1; })
-
-#Build Agora
-RUN mkdir /agora/build 
-
-RUN (cd agora \
-    cd build \
-    cmake .. \
-    make -j \
-    )
-
-# #Make the saopy settings a lower priority
-# RUN mv /usr/local/lib/sysctl.d/SoapySDRServer.conf /usr/local/lib/sysctl.d/98-SoapySDRServer.conf
-# #Ethernet buffer sizes
-# RUN echo -e '# Ethernet transport tuning\n# Socket Rx Buffer Max Size\nnet.core.rmem_max=536870912\n#Socket Send Buffer Max Size\nnet.core.wmem_max=536870912' | tee /etc/sysctl.d/99-agora.conf
-# RUN sysctl --load /etc/sysctl.d/99-agora.conf
-
-# RUN echo -e '#!/usr/bin/bash\nsource /opt/intel/oneapi/setvars.sh --config="/opt/intel/oneapi/renew-config.txt"' | sudo tee /etc/profile.d/10-inteloneapivars.sh
-# RUN echo -e '#!/usr/bin/bash\nsudo chown -R $(id -u):$(id -g) /scratch/ > /dev/null 2>&1' | sudo tee /etc/profile.d/11-scratchowner.sh
-
-
-# RUN echo -e 'intelpython=exclude' | tee /opt/intel/oneapi/renew-config.txt
-# RUN echo -e '#!/usr/bin/bash\nsource /opt/intel/oneapi/setvars.sh --config="/opt/intel/oneapi/renew-config.txt"' | tee /etc/profile.d/10-inteloneapivars.sh
-
 # Undo the noninteractive DEBIAN_FRONTEND from the beginning of this file
 ENV DEBIAN_FRONTEND teletype
-
-# # Set up the intel MKL compiler variables (shell environment vars) so that Agora can run.
-# # This is only really needed when logging into the container via a remote bash shell and manually running commands.
-# # Note that this will NOT take effect if a docker CMD or kubernetes command is used directly.
-# RUN echo "source /opt/intel/compilers_and_libraries/linux/bin/compilervars.sh intel64" >> ~/.bashrc
-
